# Generated by Django 6.0.4 on 2026-04-22 23:57

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='invite_code',
            field=models.CharField(default=api.models.generate_invite_code, max_length=10, unique=True),
        ),
    ]
